num_of_Exception : Exception -> {'e, (0 <= 'e & 'e <= 18). int('e)}